### PR TITLE
propose rfc binaries kata

### PR DESCRIPTION
**Pull request by OleMchls**
Any opinions on this one?

Might be too though. I assume besides me no one cares about binary, that much :D

That could be fixed with some more hints on general conversion.

### CODE REVIEW

**Comment by OleMchls** [comment]
I know I'm going to spoil this for you (sorry!) but @bjro and @h4cc what do you both think?

**Comment by h4cc** [comment]
The idea is to create a custom sigil (http://elixir-lang.org/getting-started/sigils.html#custom-sigils) that can convert from `1064 9cbf` to `.d..`? I am not sure if this will work without tests...

Also having a short introduction to sigils might be very handy.

**Comment by BjRo** [comment]
Personally I would be interested in figuring out how custom Sigils work (since I've never used them). I second @h4cc though regarding the concern for using this kata for tomorrow. The jump (w/o introduction to Sigils and tests) might be a bit high, given where we are coming from the last meeting. 

In the end it's just a gut feeling. I don't have any strong objections against trying this out ;-)

**Comment by OleMchls** [comment]
@h4cc I agree that the task is not very well described, sorry for that. The idea is to have the sign to create a working elixir binary representation from this. so

``` elixir
~b(ff) == << 0xff>>
```

That is of cause the simplest case, and everything after the pipe `|` should be treated as a comment

**Pull request closed without merging**
